# Form implementation generated from reading ui file 'energy_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_energyScreen(object):
    def setupUi(self, energyScreen):
        energyScreen.setObjectName("energyScreen")
        energyScreen.resize(335, 300)
        energyScreen.setStyleSheet("background-color: #E0E5EC;")
        self.btn_to_temp = QtWidgets.QPushButton(parent=energyScreen)
        self.btn_to_temp.setGeometry(QtCore.QRect(150, 250, 121, 41))
        self.btn_to_temp.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F5F5F5, stop:1 #E0E0E0); \n"
"color: #444444;\n"
"border-radius: 4px;\n"
"padding: 8px 16px;\n"
"font-size: 12px;\n"
"border: 1px solid #B0B0B0;\n"
"border-bottom: 2px solid #CFCFCF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D0D0D0, stop:1 #E5E5E5); \n"
"border-top: 3px solid #A0A0A0;\n"
"border-left: 3px solid #A8A8A8;\n"
"border-right: 3px solid #F0F0F0;\n"
"border-bottom: 3px solid #F8F8F8;\n"
"\n"
"padding-left: 18px;\n"
"padding-top: 11px;\n"
"color: #005A9E;\n"
"}")
        self.btn_to_temp.setObjectName("btn_to_temp")
        self.groupBox_8 = QtWidgets.QGroupBox(parent=energyScreen)
        self.groupBox_8.setGeometry(QtCore.QRect(40, 20, 251, 171))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #bdc3c7; /* 테두리 색상 */\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"    margin-top: 15px; /* 타이틀 공간 확보 */\n"
"    background-color: #E0E5EC; /* 배경색 */\n"
"    padding: 10px;\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    \n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* 타이틀 위치 */\n"
"    padding: 0 5px;\n"
"    color: #2c3e50; /* 타이틀 글자 색상 */\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.lbl_power = QtWidgets.QLabel(parent=self.groupBox_8)
        self.lbl_power.setGeometry(QtCore.QRect(110, 30, 111, 31))
        self.lbl_power.setStyleSheet("QLabel {\n"
"   /* 1. 배경을 주변보다 살짝 어둡게 (푹 패인 바닥 역활) */\n"
"    /*background-color: #D6DCE5; /* 배경색 */\n"
"    background-color: #1a1a1b;\n"
"   /* 2. 빛의 반대 방향 (좌상단)은 그림자가 져서 어둡게 */\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    /* 3. 빛이 닿는 방향(우하단)은 밝게 빛나도록 */\n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"   \n"
"    /* 4. 부드러운 곡선과 텍스트 설정 */\n"
"    border-radius: 1px; /* 둥근 모서리 */\n"
"    padding: 1px; /* 내부 여백 */\n"
"    /*color: #4A5568; /* 글자색 */\n"
"    color: #00ffcc;\n"
"    font-family: \'Pretendard\', sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    \n"
"}")
        self.lbl_power.setText("")
        self.lbl_power.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_power.setObjectName("lbl_power")
        self.Test_25 = QtWidgets.QLabel(parent=self.groupBox_8)
        self.Test_25.setGeometry(QtCore.QRect(20, 30, 71, 23))
        self.Test_25.setObjectName("Test_25")
        self.lbl_energy = QtWidgets.QLabel(parent=self.groupBox_8)
        self.lbl_energy.setGeometry(QtCore.QRect(110, 70, 111, 31))
        self.lbl_energy.setStyleSheet("QLabel {\n"
"   /* 1. 배경을 주변보다 살짝 어둡게 (푹 패인 바닥 역활) */\n"
"    /*background-color: #D6DCE5; /* 배경색 */\n"
"    background-color: #1a1a1b;\n"
"   /* 2. 빛의 반대 방향 (좌상단)은 그림자가 져서 어둡게 */\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    /* 3. 빛이 닿는 방향(우하단)은 밝게 빛나도록 */\n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"   \n"
"    /* 4. 부드러운 곡선과 텍스트 설정 */\n"
"    border-radius: 1px; /* 둥근 모서리 */\n"
"    padding: 1px; /* 내부 여백 */\n"
"    /*color: #4A5568; /* 글자색 */\n"
"    color: #00ffcc;\n"
"    font-family: \'Pretendard\', sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    \n"
"}")
        self.lbl_energy.setText("")
        self.lbl_energy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_energy.setObjectName("lbl_energy")
        self.Test_24 = QtWidgets.QLabel(parent=self.groupBox_8)
        self.Test_24.setGeometry(QtCore.QRect(20, 70, 81, 23))
        self.Test_24.setObjectName("Test_24")
        self.btn_start_power = QtWidgets.QPushButton(parent=self.groupBox_8)
        self.btn_start_power.setGeometry(QtCore.QRect(20, 120, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_start_power.setFont(font)
        self.btn_start_power.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_start_power.setObjectName("btn_start_power")
        self.btn_stop_power = QtWidgets.QPushButton(parent=self.groupBox_8)
        self.btn_stop_power.setGeometry(QtCore.QRect(130, 120, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_stop_power.setFont(font)
        self.btn_stop_power.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_stop_power.setObjectName("btn_stop_power")
        self.btn_power_test = QtWidgets.QPushButton(parent=energyScreen)
        self.btn_power_test.setGeometry(QtCore.QRect(60, 200, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_power_test.setFont(font)
        self.btn_power_test.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_power_test.setObjectName("btn_power_test")
        self.btn_to_main = QtWidgets.QPushButton(parent=energyScreen)
        self.btn_to_main.setGeometry(QtCore.QRect(20, 250, 121, 41))
        self.btn_to_main.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F5F5F5, stop:1 #E0E0E0); \n"
"color: #444444;\n"
"border-radius: 4px;\n"
"padding: 8px 16px;\n"
"font-size: 12px;\n"
"border: 1px solid #B0B0B0;\n"
"border-bottom: 2px solid #CFCFCF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D0D0D0, stop:1 #E5E5E5); \n"
"border-top: 3px solid #A0A0A0;\n"
"border-left: 3px solid #A8A8A8;\n"
"border-right: 3px solid #F0F0F0;\n"
"border-bottom: 3px solid #F8F8F8;\n"
"\n"
"padding-left: 18px;\n"
"padding-top: 11px;\n"
"color: #005A9E;\n"
"}")
        self.btn_to_main.setObjectName("btn_to_main")

        self.retranslateUi(energyScreen)
        QtCore.QMetaObject.connectSlotsByName(energyScreen)

    def retranslateUi(self, energyScreen):
        _translate = QtCore.QCoreApplication.translate
        energyScreen.setWindowTitle(_translate("energyScreen", "Dialog"))
        self.btn_to_temp.setText(_translate("energyScreen", "Temp Contol"))
        self.groupBox_8.setTitle(_translate("energyScreen", "전력량계 시뮬레이션"))
        self.Test_25.setText(_translate("energyScreen", "<html><head/><body><p>현재 전력량</p></body></html>"))
        self.Test_24.setText(_translate("energyScreen", "<html><head/><body><p>적산 전력량</p></body></html>"))
        self.btn_start_power.setText(_translate("energyScreen", "Start"))
        self.btn_stop_power.setText(_translate("energyScreen", "Stop"))
        self.btn_power_test.setText(_translate("energyScreen", "Test"))
        self.btn_to_main.setText(_translate("energyScreen", "Main Screen"))
