# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_historyScreen(object):
    def setupUi(self, historyScreen):
        historyScreen.setObjectName("historyScreen")
        historyScreen.resize(1496, 670)
        historyScreen.setStyleSheet("background-color: #E0E5EC;")
        self.table_history = QtWidgets.QTableWidget(parent=historyScreen)
        self.table_history.setGeometry(QtCore.QRect(20, 90, 1331, 481))
        self.table_history.setDragEnabled(True)
        self.table_history.setAlternatingRowColors(True)
        self.table_history.setRowCount(15)
        self.table_history.setObjectName("table_history")
        self.table_history.setColumnCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(12, item)
        self.btn_to_main = QtWidgets.QPushButton(parent=historyScreen)
        self.btn_to_main.setGeometry(QtCore.QRect(30, 600, 121, 41))
        self.btn_to_main.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F5F5F5, stop:1 #E0E0E0); \n"
"color: #444444;\n"
"border-radius: 4px;\n"
"padding: 8px 16px;\n"
"font-size: 12px;\n"
"border: 1px solid #B0B0B0;\n"
"border-bottom: 2px solid #CFCFCF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D0D0D0, stop:1 #E5E5E5); \n"
"border-top: 3px solid #A0A0A0;\n"
"border-left: 3px solid #A8A8A8;\n"
"border-right: 3px solid #F0F0F0;\n"
"border-bottom: 3px solid #F8F8F8;\n"
"\n"
"padding-left: 18px;\n"
"padding-top: 11px;\n"
"color: #005A9E;\n"
"}")
        self.btn_to_main.setObjectName("btn_to_main")

        self.retranslateUi(historyScreen)
        QtCore.QMetaObject.connectSlotsByName(historyScreen)

    def retranslateUi(self, historyScreen):
        _translate = QtCore.QCoreApplication.translate
        historyScreen.setWindowTitle(_translate("historyScreen", "Dialog"))
        item = self.table_history.verticalHeaderItem(0)
        item.setText(_translate("historyScreen", "1"))
        item = self.table_history.verticalHeaderItem(1)
        item.setText(_translate("historyScreen", "2"))
        item = self.table_history.verticalHeaderItem(2)
        item.setText(_translate("historyScreen", "3"))
        item = self.table_history.verticalHeaderItem(3)
        item.setText(_translate("historyScreen", "4"))
        item = self.table_history.horizontalHeaderItem(0)
        item.setText(_translate("historyScreen", "Mon"))
        item = self.table_history.horizontalHeaderItem(1)
        item.setText(_translate("historyScreen", "Day"))
        item = self.table_history.horizontalHeaderItem(2)
        item.setText(_translate("historyScreen", "Q\'ty"))
        item = self.table_history.horizontalHeaderItem(3)
        item.setText(_translate("historyScreen", "생산"))
        item = self.table_history.horizontalHeaderItem(4)
        item.setText(_translate("historyScreen", "비가동"))
        item = self.table_history.horizontalHeaderItem(5)
        item.setText(_translate("historyScreen", "SaveMode"))
        item = self.table_history.horizontalHeaderItem(6)
        item.setText(_translate("historyScreen", "ShutDown"))
        item = self.table_history.horizontalHeaderItem(7)
        item.setText(_translate("historyScreen", "Total"))
        item = self.table_history.horizontalHeaderItem(8)
        item.setText(_translate("historyScreen", "생산"))
        item = self.table_history.horizontalHeaderItem(9)
        item.setText(_translate("historyScreen", "비가동"))
        item = self.table_history.horizontalHeaderItem(10)
        item.setText(_translate("historyScreen", "SaveMode"))
        item = self.table_history.horizontalHeaderItem(11)
        item.setText(_translate("historyScreen", "ShutDown"))
        item = self.table_history.horizontalHeaderItem(12)
        item.setText(_translate("historyScreen", "Total"))
        self.btn_to_main.setText(_translate("historyScreen", "Main Screen"))
