# Form implementation generated from reading ui file 'temp_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TempScreen(object):
    def setupUi(self, TempScreen):
        TempScreen.setObjectName("TempScreen")
        TempScreen.resize(362, 318)
        TempScreen.setStyleSheet("background-color: #E0E5EC;")
        self.btn_to_main = QtWidgets.QPushButton(parent=TempScreen)
        self.btn_to_main.setGeometry(QtCore.QRect(50, 260, 121, 41))
        self.btn_to_main.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F5F5F5, stop:1 #E0E0E0); \n"
"color: #444444;\n"
"border-radius: 4px;\n"
"padding: 8px 16px;\n"
"font-size: 12px;\n"
"border: 1px solid #B0B0B0;\n"
"border-bottom: 2px solid #CFCFCF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D0D0D0, stop:1 #E5E5E5); \n"
"border-top: 3px solid #A0A0A0;\n"
"border-left: 3px solid #A8A8A8;\n"
"border-right: 3px solid #F0F0F0;\n"
"border-bottom: 3px solid #F8F8F8;\n"
"\n"
"padding-left: 18px;\n"
"padding-top: 11px;\n"
"color: #005A9E;\n"
"}")
        self.btn_to_main.setObjectName("btn_to_main")
        self.btn_value = QtWidgets.QPushButton(parent=TempScreen)
        self.btn_value.setGeometry(QtCore.QRect(60, 200, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_value.setFont(font)
        self.btn_value.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_value.setObjectName("btn_value")
        self.groupBox_9 = QtWidgets.QGroupBox(parent=TempScreen)
        self.groupBox_9.setGeometry(QtCore.QRect(50, 20, 251, 171))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #bdc3c7; /* 테두리 색상 */\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"    margin-top: 15px; /* 타이틀 공간 확보 */\n"
"    background-color: #E0E5EC; /* 배경색 */\n"
"    padding: 10px;\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    \n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* 타이틀 위치 */\n"
"    padding: 0 5px;\n"
"    color: #2c3e50; /* 타이틀 글자 색상 */\n"
"}")
        self.groupBox_9.setObjectName("groupBox_9")
        self.lbl_tempCurrValue = QtWidgets.QLabel(parent=self.groupBox_9)
        self.lbl_tempCurrValue.setGeometry(QtCore.QRect(110, 30, 111, 31))
        self.lbl_tempCurrValue.setStyleSheet("QLabel {\n"
"   /* 1. 배경을 주변보다 살짝 어둡게 (푹 패인 바닥 역활) */\n"
"    /*background-color: #D6DCE5; /* 배경색 */\n"
"    background-color: #1a1a1b;\n"
"   /* 2. 빛의 반대 방향 (좌상단)은 그림자가 져서 어둡게 */\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    /* 3. 빛이 닿는 방향(우하단)은 밝게 빛나도록 */\n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"   \n"
"    /* 4. 부드러운 곡선과 텍스트 설정 */\n"
"    border-radius: 1px; /* 둥근 모서리 */\n"
"    padding: 1px; /* 내부 여백 */\n"
"    /*color: #4A5568; /* 글자색 */\n"
"    color: #00ffcc;\n"
"    font-family: \'Pretendard\', sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    \n"
"}")
        self.lbl_tempCurrValue.setText("")
        self.lbl_tempCurrValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_tempCurrValue.setObjectName("lbl_tempCurrValue")
        self.Test_26 = QtWidgets.QLabel(parent=self.groupBox_9)
        self.Test_26.setGeometry(QtCore.QRect(20, 30, 71, 23))
        self.Test_26.setObjectName("Test_26")
        self.Test_27 = QtWidgets.QLabel(parent=self.groupBox_9)
        self.Test_27.setGeometry(QtCore.QRect(20, 70, 81, 23))
        self.Test_27.setObjectName("Test_27")
        self.btn_start_temp = QtWidgets.QPushButton(parent=self.groupBox_9)
        self.btn_start_temp.setGeometry(QtCore.QRect(20, 120, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_start_temp.setFont(font)
        self.btn_start_temp.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_start_temp.setObjectName("btn_start_temp")
        self.btn_stop_temp = QtWidgets.QPushButton(parent=self.groupBox_9)
        self.btn_stop_temp.setGeometry(QtCore.QRect(130, 120, 84, 38))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setItalic(False)
        self.btn_stop_temp.setFont(font)
        self.btn_stop_temp.setStyleSheet("QPushButton {\n"
"background-color: #e0e0e0;  /* 부모위젯의 배경색과 맞춰주세요 */\n"
"border-radius: 12px;\n"
"border: none;\n"
"\n"
"/* Qt에서는 복합 그림자가 안 되므로 테두리 색상차이를 이용 */\n"
"border-top: 2px solid #ffffff;\n"
"border-left: 2px solid #ffffff;\n"
"border-right: 2px solid #bebebe;  /* 오른쪽 아래 어두운 그림자*/\n"
"border-bottom: 2px solid #bebebe;\n"
"\n"
"color: #606060;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"/* 눌렸을 때는 반대로 어두운 쪽이 위로 오게 하여 \'파인\'느낌 생성*/\n"
"border-top: 2px solid #bebebe;\n"
"border-left: 2px solid #bebebe;\n"
"border-right: 2px solid #ffffff;\n"
"border-bottom: 2px solid #ffffff;\n"
"background-color: #e0e0e0;  \n"
"\n"
"}")
        self.btn_stop_temp.setObjectName("btn_stop_temp")
        self.ledit_temp_target = QtWidgets.QLineEdit(parent=self.groupBox_9)
        self.ledit_temp_target.setGeometry(QtCore.QRect(110, 70, 111, 31))
        self.ledit_temp_target.setStyleSheet("/* 1. 배경을 주변보다 살짝 어둡게 (푹 패인 바닥 역활) */\n"
"    /*background-color: #D6DCE5; /* 배경색 */\n"
"    background-color: #1a1a1b;\n"
"   /* 2. 빛의 반대 방향 (좌상단)은 그림자가 져서 어둡게 */\n"
"    border-top: 2px solid #B0B9C6;\n"
"    border-left: 2px solid #B0B9C6;\n"
"  \n"
"    /* 3. 빛이 닿는 방향(우하단)은 밝게 빛나도록 */\n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    border-right: 2px solid #FFFFFF;\n"
"   \n"
"    /* 4. 부드러운 곡선과 텍스트 설정 */\n"
"    border-radius: 1px; /* 둥근 모서리 */\n"
"    padding: 1px; /* 내부 여백 */\n"
"    /*color: #4A5568; /* 글자색 */\n"
"    color: #00ffcc;\n"
"    font-family: \'Pretendard\', sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;")
        self.ledit_temp_target.setObjectName("ledit_temp_target")
        self.btn_to_Energy = QtWidgets.QPushButton(parent=TempScreen)
        self.btn_to_Energy.setGeometry(QtCore.QRect(180, 260, 121, 41))
        self.btn_to_Energy.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F5F5F5, stop:1 #E0E0E0); \n"
"color: #444444;\n"
"border-radius: 4px;\n"
"padding: 8px 16px;\n"
"font-size: 12px;\n"
"border: 1px solid #B0B0B0;\n"
"border-bottom: 2px solid #CFCFCF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #D0D0D0, stop:1 #E5E5E5); \n"
"border-top: 3px solid #A0A0A0;\n"
"border-left: 3px solid #A8A8A8;\n"
"border-right: 3px solid #F0F0F0;\n"
"border-bottom: 3px solid #F8F8F8;\n"
"\n"
"padding-left: 18px;\n"
"padding-top: 11px;\n"
"color: #005A9E;\n"
"}")
        self.btn_to_Energy.setObjectName("btn_to_Energy")

        self.retranslateUi(TempScreen)
        QtCore.QMetaObject.connectSlotsByName(TempScreen)

    def retranslateUi(self, TempScreen):
        _translate = QtCore.QCoreApplication.translate
        TempScreen.setWindowTitle(_translate("TempScreen", "Dialog"))
        self.btn_to_main.setText(_translate("TempScreen", "Main Screen"))
        self.btn_value.setText(_translate("TempScreen", "Start"))
        self.groupBox_9.setTitle(_translate("TempScreen", "온도 컨트롤 시뮬레이션"))
        self.Test_26.setText(_translate("TempScreen", "<html><head/><body><p>현재 온도</p></body></html>"))
        self.Test_27.setText(_translate("TempScreen", "<html><head/><body><p>설정 온도</p></body></html>"))
        self.btn_start_temp.setText(_translate("TempScreen", "Start"))
        self.btn_stop_temp.setText(_translate("TempScreen", "Stop"))
        self.btn_to_Energy.setText(_translate("TempScreen", "Energy Meter"))
